pipeline:
  name: Build Harness
  identifier: Build_SanjayMolankal_Harness_1758173712528
  projectIdentifier: Maven3
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1758111779450
        repoName: SanjayMolankal/Harness
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              image: maven:3.9.4-eclipse-temurin-17
          execution:
            steps:
              - step:
                  type: Run
                  name: Build with Maven
                  identifier: Build_Maven
                  spec:
                    shell: Sh
                    command: |
                      echo "Building Maven Project..."
                      mvn clean install -Dmaven.test.failure.ignore=false
                      ls -lh target/
